-- Initialize all 13 microservice databases for Hotel Management System
CREATE DATABASE IF NOT EXISTS auth_db;
CREATE DATABASE IF NOT EXISTS guest_db;
CREATE DATABASE IF NOT EXISTS room_db;
CREATE DATABASE IF NOT EXISTS reservation_db;
CREATE DATABASE IF NOT EXISTS payment_db;
CREATE DATABASE IF NOT EXISTS billing_db;
CREATE DATABASE IF NOT EXISTS rate_db;
CREATE DATABASE IF NOT EXISTS staff_db;
CREATE DATABASE IF NOT EXISTS inventory_db;
CREATE DATABASE IF NOT EXISTS guest_experience_db;
CREATE DATABASE IF NOT EXISTS operations_db;
CREATE DATABASE IF NOT EXISTS reporting_db;
CREATE DATABASE IF NOT EXISTS notification_db;

GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';
FLUSH PRIVILEGES;
